
#SRCS_TEST += $(TEST_ROOT_PATH)/ringbuffer_test.c
SRCS_TEST += $(TEST_ROOT_PATH)/uart_test.c
SRCS_TEST += $(TEST_ROOT_PATH)/sd_test.c
#SRCS_TEST += $(TEST_ROOT_PATH)/list_test.c
#SRCS_TEST += $(TEST_ROOT_PATH)/sem_test.c
#SRCS_TEST += $(TEST_ROOT_PATH)/poll_test.c
SRCS_TEST += $(TEST_ROOT_PATH)/sbus_test.c
SRCS_TEST += $(TEST_ROOT_PATH)/spi_test.c
SRCS_TEST += $(TEST_ROOT_PATH)/imu_test.c

OBJS_TEST += $(SRCS_TEST:%.c=%.o)
