
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSM.
* Version: 
* DO NOT EDIT.
*
*  v (64-bit)
SW Build (by ) on 
Copyright 1986-2014 Xilinx, Inc. All Rights Reserved.
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xuartps.h"

/*
* The configuration table for devices
*/

XUartPs_Config XUartPs_ConfigTable[] =
{
	{
		XPAR_PS7_UART_0_DEVICE_ID,
		XPAR_PS7_UART_0_BASEADDR,
		XPAR_PS7_UART_0_UART_CLK_FREQ_HZ,
		XPAR_PS7_UART_0_HAS_MODEM
	},
	{
		XPAR_PS7_UART_1_DEVICE_ID,
		XPAR_PS7_UART_1_BASEADDR,
		XPAR_PS7_UART_1_UART_CLK_FREQ_HZ,
		XPAR_PS7_UART_1_HAS_MODEM
	}
};


